using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class PlayerController : MonoBehaviour
{
    private Vector2 startPoint;
    private float horizontal;
    private float speed = 8f;
    private float jumpingPower = 16f;
    private bool isFacingRight = true;
    public Vector2 debug;

    [SerializeField] private Text gemsText;
    [SerializeField] private Text levelText;
    [SerializeField] private Text guideText;

    AudioController audioController;

    public Animator animator;
    public int gems = 0;
    public bool isJumping = false;
    public bool isFalling = false;
    public bool isRunning = false;
    public bool isHurted = false;

    [SerializeField] private Rigidbody2D rb;
    [SerializeField] private Transform groundCheck;
    [SerializeField] private LayerMask groundLayer;

    private void Awake()
    {
        audioController = GameObject.FindGameObjectWithTag("Audio").GetComponent<AudioController>();
    }

    public void frezen()
    {
        speed = 0;
        jumpingPower = 0;
    }

    // gem trigger
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("Gem"))
        {
            Destroy(collision.gameObject);
            audioController.PlaySFX(audioController.cherryClip); // Nếu bạn đổi tên audioClip, sửa lại ở đây
            gems++;

            if (SceneManager.GetActiveScene().name == "Tutorial")
            {
                gemsText.text = "Gems: " + gems + "/1";
            }
            else
            {
                gemsText.text = "Gems: " + gems + "/" + (2 * (SceneManager.GetActiveScene().buildIndex) + 3);
            }
        }

        if (collision.gameObject.CompareTag("guide"))
        {
            guideText.text = "Hãy dùng quái làm bước đệm";
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("guide"))
        {
            guideText.text = "";
        }
    }

    // enemy trigger
    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Enemy"))
        {
            if (isFalling)
            {
                audioController.PlaySFX(audioController.killClip);

                if (collision.gameObject.GetComponent<FrogController>() != null)
                {
                    FrogController frog = collision.gameObject.GetComponent<FrogController>();
                    frog.Triggle();
                }
                else if (collision.gameObject.GetComponent<eagleController>() != null)
                {
                    eagleController eagle = collision.gameObject.GetComponent<eagleController>();
                    eagle.Triggle();
                }
                else if (collision.gameObject.GetComponent<OpController>() != null)
                {
                    OpController op = collision.gameObject.GetComponent<OpController>();
                    op.Triggle();
                }

                rb.velocity = new Vector2(rb.velocity.x, jumpingPower);
            }
            else
            {
                speed = 0;
                jumpingPower = 0;
                isHurted = true;
            }
        }

        if (collision.gameObject.CompareTag("trap"))
        {
            speed = 0;
            jumpingPower = 0;
            isHurted = true;
        }
    }

    private void Respawn()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);
    }

    private void Start()
    {
        if (SceneManager.GetActiveScene().name == "Tutorial")
        {
            gemsText.text = "Gems: 0/1";
        }
        else
        {
            gemsText.text = "Gems: 0/" + (2 * (SceneManager.GetActiveScene().buildIndex) + 3);
            levelText.text = "Level: " + (SceneManager.GetActiveScene().buildIndex);
        }

        startPoint = transform.position;
    }

    void Update()
    {
        horizontal = Input.GetAxisRaw("Horizontal");

        if (Input.GetButtonDown("Jump") && IsGrounded())
        {
            rb.velocity = new Vector2(rb.velocity.x, jumpingPower);
        }

        if (Input.GetButtonUp("Jump") && rb.velocity.y > 0f)
        {
            rb.velocity = new Vector2(rb.velocity.x, rb.velocity.y * 0.5f);
        }

        if (rb.velocity.y < 0f && !IsGrounded())
        {
            isFalling = true;
        }
        else
        {
            isFalling = false;
        }

        isRunning = Mathf.Abs(horizontal) > 0f;

        animator.SetBool("isRunning", isRunning);
        animator.SetBool("isJumping", isJumping);
        animator.SetBool("IsFalling", isFalling);
        animator.SetBool("isHurted", isHurted);

        Flip();
    }

    private void FixedUpdate()
    {
        rb.velocity = new Vector2(horizontal * speed, rb.velocity.y);

        isJumping = !IsGrounded();
        if (isFalling && IsGrounded())
        {
            isFalling = false;
        }
    }

    private bool IsGrounded()
    {
        return Physics2D.OverlapCircle(groundCheck.position, 0.2f, groundLayer);
    }

    private void Flip()
    {
        if (isFacingRight && horizontal < 0f || !isFacingRight && horizontal > 0f)
        {
            isFacingRight = !isFacingRight;
            Vector3 localScale = transform.localScale;
            localScale.x *= -1f;
            transform.localScale = localScale;
        }
    }

    public void RunAudio()
    {
        audioController.PlaySFX(audioController.runClip);
    }

    public void JumpAudio()
    {
        audioController.PlaySFX(audioController.jumpClip);
    }

    public void deathAudio()
    {
        audioController.PlaySFX(audioController.hurtClip);
    }
}
